// Builds the crawlable French and German home pages, fr/index.html and de/index.html,
// from index.html (English, the source) and assets/i18n.js (FR/DE strings).
// Run after any change to either file:  node tools/build-locales.mjs
// tools/check-locales.mjs fails when the committed pages are out of date.
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import vm from 'node:vm';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const SITE = 'https://webwerk.lu';
export const LOCALES = {
  fr: { path: '/fr/', og: 'fr_LU' },
  de: { path: '/de/', og: 'de_LU' },
};
const OG_EN = 'en_GB';

const esc = s => s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
const attr = s => esc(s).replace(/"/g, '&quot;');

export function loadDict() {
  const src = readFileSync(join(ROOT, 'assets/i18n.js'), 'utf8');
  const ctx = { window: {} };
  vm.runInNewContext(src, ctx);
  return ctx.window.WW_I18N;
}

// Replace exactly one match of re in html, or throw: a silent miss would ship an English tag on a French page.
function once(html, re, fn, what) {
  let n = 0;
  const out = html.replace(re, (...m) => { n++; return fn(...m); });
  if (n !== 1) throw new Error(`${what}: expected 1 match, found ${n}`);
  return out;
}

function need(dict, key, lang) {
  const v = dict[key];
  if (!v) throw new Error(`assets/i18n.js ${lang}.${key} is missing; the ${lang} page needs it`);
  return v;
}

export function render(lang, html, dict) {
  const L = LOCALES[lang], T = dict[lang], url = SITE + L.path;
  const title = need(T, 'meta_title', lang), desc = need(T, 'meta_desc', lang), ogDesc = need(T, 'og_desc', lang);

  html = once(html, /<html lang="en">/, () => `<html lang="${lang}">`, 'html lang');
  html = once(html, /<link rel="canonical" href="https:\/\/webwerk\.lu\/">/, () => `<link rel="canonical" href="${url}">`, 'canonical');
  html = once(html, /<title>[^<]*<\/title>/, () => `<title>${esc(title)}</title>`, 'title');
  html = once(html, /<meta name="description" content="[^"]*">/, () => `<meta name="description" content="${attr(desc)}">`, 'meta description');
  html = once(html, /<meta property="og:title" content="[^"]*">/, () => `<meta property="og:title" content="${attr(title)}">`, 'og:title');
  html = once(html, /<meta property="og:description" content="[^"]*">/, () => `<meta property="og:description" content="${attr(ogDesc)}">`, 'og:description');
  html = once(html, /<meta property="og:url" content="[^"]*">/, () => `<meta property="og:url" content="${url}">`, 'og:url');
  html = once(html, /<meta name="twitter:title" content="[^"]*">/, () => `<meta name="twitter:title" content="${attr(title)}">`, 'twitter:title');
  html = once(html, /<meta name="twitter:description" content="[^"]*">/, () => `<meta name="twitter:description" content="${attr(ogDesc)}">`, 'twitter:description');
  // og:locale: this page's locale first, the other two as alternates
  const others = [OG_EN, ...Object.entries(LOCALES).filter(([k]) => k !== lang).map(([, v]) => v.og)];
  html = once(html, /<meta property="og:locale" content="[^"]*">(?:\s*<meta property="og:locale:alternate" content="[^"]*">)+/,
    () => [`<meta property="og:locale" content="${L.og}">`, ...others.map(o => `<meta property="og:locale:alternate" content="${o}">`)].join('\n'), 'og:locale block');
  html = once(html, /"description":"Design studio in Luxembourg\."/, () => `"description":${JSON.stringify(need(T, 'lead', lang))}`, 'JSON-LD description');

  // language switch: the current language carries aria-current
  html = once(html, /(<div class="lang">)([\s\S]*?)(<\/div>)/, (m, a, links, b) =>
    a + links.replace(/ aria-current="true"/g, '').replace(new RegExp(`(<a href="[^"]*")( lang="${lang}")`), '$1 aria-current="true"$2') + b, 'language switch');

  // every data-t element: the translated text, with the English kept in data-en for the in-page switch
  html = html.replace(/(<(\w+)\b[^>]*\sdata-t="([a-z0-9_]+)")([^>]*>)([^<]*)(<\/\2>)/g, (m, open, tag, key, rest, text, close) => {
    const tr = T[key];
    return tr ? `${open} data-en="${text.replace(/"/g, '&quot;')}"${rest}${esc(tr)}${close}` : m;
  });

  // the first work caption is set by script; bake it in so the page reads right without it
  html = once(html, /(<span class="k1-l">)([^<]*)(<\/span>)/, (m, a, t, b) => a + esc(need(T, 'cap0', lang)) + b, 'work caption');

  // the note goes after the doctype: anything before it would put the page in quirks mode
  return once(html, /^<!doctype html>\r?\n/i, m => m + '<!-- Generated by tools/build-locales.mjs from index.html + assets/i18n.js. Do not edit; edit those and rebuild. -->\n', 'doctype');
}

export function buildAll() {
  const html = readFileSync(join(ROOT, 'index.html'), 'utf8'), dict = loadDict();
  return Object.fromEntries(Object.keys(LOCALES).map(l => [`${l}/index.html`, render(l, html, dict)]));
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  for (const [file, out] of Object.entries(buildAll())) {
    mkdirSync(join(ROOT, dirname(file)), { recursive: true });
    writeFileSync(join(ROOT, file), out);
    console.log('wrote', file);
  }
}
